2025-01-15 18:41:14 [ERROR]: uncaughtException: Invalid status code: Invalid status code: Users retrieved successfully
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Invalid status code: Users retrieved successfully
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.getUsers (D:\pratice\node-server\controllers\userController.js:30:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:49:06 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:14:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:49:18 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:14:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:49:52 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:14:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:50:14 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:17:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:52:16 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:23:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:53:15 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:23:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:55:38 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:23:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:57:49 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:23:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 18:59:25 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:23:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 19:00:34 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:23:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 19:03:30 [ERROR]: uncaughtException: Invalid status code: Error creating user
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: Error creating user
    at ServerResponse.writeHead (node:_http_server:352:11)
    at ServerResponse.writeHead (D:\pratice\node-server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:338:8)
    at write_ (node:_http_outgoing:919:9)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at sendResponse (D:\pratice\node-server\helpers\responseHelper.js:9:24)
    at exports.createUser (D:\pratice\node-server\controllers\userController.js:26:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-15 21:32:42 [ERROR]: uncaughtException: groupRoutes is not defined
ReferenceError: groupRoutes is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-15 21:32:58 [ERROR]: uncaughtException: groupRoutes is not defined
ReferenceError: groupRoutes is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-15 21:33:02 [ERROR]: uncaughtException: groupRoutes is not defined
ReferenceError: groupRoutes is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-15 21:33:04 [ERROR]: uncaughtException: groupRoutes is not defined
ReferenceError: groupRoutes is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-15 21:33:12 [ERROR]: uncaughtException: groupRoutes is not defined
ReferenceError: groupRoutes is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-15 21:33:19 [ERROR]: uncaughtException: groupRoutes is not defined
ReferenceError: groupRoutes is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-15 21:33:26 [ERROR]: uncaughtException: groupRoutes is not defined
ReferenceError: groupRoutes is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-15 21:34:27 [ERROR]: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\messageRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:14:23)
2025-01-15 21:36:36 [ERROR]: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\messageRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:14:23)
2025-01-15 21:37:53 [ERROR]: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\messageRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:14:23)
2025-01-15 21:38:02 [ERROR]: uncaughtException: Route.post() requires a callback function but got a [object Undefined]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as post] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\messageRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:14:23)
2025-01-15 21:38:07 [ERROR]: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\messageRoutes.js:11:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:14:23)
2025-01-15 21:38:18 [ERROR]: uncaughtException: Missing catch or finally after try
D:\pratice\node-server\controllers\messageController.js:30
};
^

SyntaxError: Missing catch or finally after try
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\messageRoutes.js:2:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-15 21:38:45 [ERROR]: uncaughtException: Unexpected token ';'
D:\pratice\node-server\controllers\messageController.js:10
        const senderId = ;
                         ^

SyntaxError: Unexpected token ';'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\messageRoutes.js:2:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-15 23:46:45 [ERROR]: uncaughtException: groupId is not defined
ReferenceError: groupId is not defined
    at Socket.<anonymous> (D:\pratice\node-server\index.js:84:15)
    at Socket.emit (node:events:514:28)
    at Socket.emitUntyped (D:\pratice\node-server\node_modules\socket.io\dist\typed-events.js:69:22)
    at D:\pratice\node-server\node_modules\socket.io\dist\socket.js:697:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2025-01-15 23:52:51 [ERROR]: uncaughtException: groupId is not defined
ReferenceError: groupId is not defined
    at Socket.<anonymous> (D:\pratice\node-server\index.js:84:15)
    at Socket.emit (node:events:514:28)
    at Socket.emitUntyped (D:\pratice\node-server\node_modules\socket.io\dist\typed-events.js:69:22)
    at D:\pratice\node-server\node_modules\socket.io\dist\socket.js:697:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2025-01-15 23:53:17 [ERROR]: uncaughtException: groupId is not defined
ReferenceError: groupId is not defined
    at Socket.<anonymous> (D:\pratice\node-server\index.js:84:15)
    at Socket.emit (node:events:514:28)
    at Socket.emitUntyped (D:\pratice\node-server\node_modules\socket.io\dist\typed-events.js:69:22)
    at D:\pratice\node-server\node_modules\socket.io\dist\socket.js:697:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2025-01-15 23:53:51 [ERROR]: uncaughtException: groupId is not defined
ReferenceError: groupId is not defined
    at Socket.<anonymous> (D:\pratice\node-server\index.js:84:15)
    at Socket.emit (node:events:514:28)
    at Socket.emitUntyped (D:\pratice\node-server\node_modules\socket.io\dist\typed-events.js:69:22)
    at D:\pratice\node-server\node_modules\socket.io\dist\socket.js:697:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2025-01-16 10:56:12 [ERROR]: uncaughtException: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\projectController.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-16 10:56:17 [ERROR]: uncaughtException: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\projectController.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-16 10:57:12 [ERROR]: uncaughtException: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\projectController.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-16 10:57:40 [ERROR]: uncaughtException: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../utils/logger'
Require stack:
- D:\pratice\node-server\controllers\projectController.js
- D:\pratice\node-server\routes\projectRoutes.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\projectController.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-16 13:06:31 [ERROR]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.<anonymous> (D:\pratice\node-server\index.js:91:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-16 13:07:10 [ERROR]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.<anonymous> (D:\pratice\node-server\index.js:91:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-16 13:11:37 [ERROR]: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:652:11)
    at ServerResponse.header (D:\pratice\node-server\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (D:\pratice\node-server\node_modules\express\lib\response.js:174:12)
    at ServerResponse.json (D:\pratice\node-server\node_modules\express\lib\response.js:278:15)
    at exports.deleteProject (D:\pratice\node-server\controllers\projectController.js:92:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-16 14:16:07 [ERROR]: uncaughtException: Cannot find module '../models/permissionsModel'
Require stack:
- D:\pratice\node-server\controllers\membersController.js
- D:\pratice\node-server\routes\membersRoutes.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../models/permissionsModel'
Require stack:
- D:\pratice\node-server\controllers\membersController.js
- D:\pratice\node-server\routes\membersRoutes.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\membersController.js:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-16 14:16:32 [ERROR]: uncaughtException: Cannot find module '../models/permissionsModel'
Require stack:
- D:\pratice\node-server\controllers\membersController.js
- D:\pratice\node-server\routes\membersRoutes.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../models/permissionsModel'
Require stack:
- D:\pratice\node-server\controllers\membersController.js
- D:\pratice\node-server\routes\membersRoutes.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\membersController.js:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-16 14:31:49 [ERROR]: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\membersRoutes.js:9:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:17:23)
2025-01-16 14:32:30 [ERROR]: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\membersRoutes.js:9:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:17:23)
2025-01-16 15:08:52 [ERROR]: uncaughtException: Cannot find module '../models/list'
Require stack:
- D:\pratice\node-server\controllers\listController.js
- D:\pratice\node-server\routes\listRoutes.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../models/list'
Require stack:
- D:\pratice\node-server\controllers\listController.js
- D:\pratice\node-server\routes\listRoutes.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\listController.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-16 16:10:58 [ERROR]: uncaughtException: Unexpected token '{'
D:\pratice\node-server\controllers\projectController.js:69
        if (!project) {
                      ^

SyntaxError: Unexpected token '{'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\projectRoutes.js:8:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-16 17:00:40 [ERROR]: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\membersRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:17:23)
2025-01-16 17:00:51 [ERROR]: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\membersRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:17:23)
2025-01-16 17:00:54 [ERROR]: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\membersRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:17:23)
2025-01-17 09:01:49 [ERROR]: uncaughtException: Cannot find module '../controllers/projectController'
Require stack:
- D:\pratice\node-server\index.js
Error: Cannot find module '../controllers/projectController'
Require stack:
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2025-01-17 09:04:18 [ERROR]: uncaughtException: Cannot find module '../controllers/projectController'
Require stack:
- D:\pratice\node-server\index.js
Error: Cannot find module '../controllers/projectController'
Require stack:
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2025-01-17 09:05:44 [ERROR]: uncaughtException: Cannot read properties of undefined (reading 'status')
TypeError: Cannot read properties of undefined (reading 'status')
    at exports.getProjectIds (D:\pratice\node-server\controllers\projectController.js:167:13)
    at Socket.<anonymous> (D:\pratice\node-server\index.js:80:32)
    at Socket.emit (node:events:514:28)
    at Socket.emitUntyped (D:\pratice\node-server\node_modules\socket.io\dist\typed-events.js:69:22)
    at D:\pratice\node-server\node_modules\socket.io\dist\socket.js:697:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2025-01-17 09:08:43 [ERROR]: uncaughtException: res is not defined
ReferenceError: res is not defined
    at exports.getProjectIds (D:\pratice\node-server\controllers\projectController.js:167:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Socket.<anonymous> (D:\pratice\node-server\index.js:80:26)
2025-01-17 09:09:19 [ERROR]: uncaughtException: group is not defined
ReferenceError: group is not defined
    at Socket.<anonymous> (D:\pratice\node-server\index.js:85:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 09:17:16 [ERROR]: uncaughtException: Cannot read properties of undefined (reading 'to')
TypeError: Cannot read properties of undefined (reading 'to')
    at Socket.<anonymous> (D:\pratice\node-server\index.js:95:22)
    at Socket.emit (node:events:514:28)
    at Socket.emitUntyped (D:\pratice\node-server\node_modules\socket.io\dist\typed-events.js:69:22)
    at D:\pratice\node-server\node_modules\socket.io\dist\socket.js:697:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2025-01-17 11:20:02 [ERROR]: uncaughtException: socketManager is not defined
ReferenceError: socketManager is not defined
    at Object.<anonymous> (D:\pratice\node-server\index.js:39:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-01-17 11:24:22 [ERROR]: uncaughtException: Unexpected token 'export'
D:\pratice\node-server\config\connectDatabase\connectDatabase.js:10
export default connectDatabase;
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:10:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:24:46 [ERROR]: uncaughtException: logger is not defined
ReferenceError: logger is not defined
    at D:\pratice\node-server\config\connectDatabase\connectDatabase.js:7:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 11:36:33 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\index.js:3
import userRoutes from './userRoutes';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:52:59 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\index.js:3
import userRoutes from './userRoutes.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:03 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\index.js:3
import userRoutes from './userRoutes.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\index.js:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:12 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\messageRoutes.js:1
import { Router } from 'express';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\index.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:17 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\messageRoutes.js:1
import { Router } from 'express';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\index.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:23 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\messageRoutes.js:1
import { Router } from 'express';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\index.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:27 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\projectRoutes.js:1
import { Router } from 'express';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\index.js:7:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:30 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\projectRoutes.js:1
import { Router } from 'express';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\index.js:7:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:34 [ERROR]: uncaughtException: Cannot use import statement outside a module
D:\pratice\node-server\routes\taskRoutes.js:1
import { Router } from 'express';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\index.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
2025-01-17 11:53:38 [ERROR]: uncaughtException: Cannot read properties of undefined (reading 'error')
TypeError: Cannot read properties of undefined (reading 'error')
    at D:\pratice\node-server\config\connectDatabase\connectDatabase.js:8:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 11:53:41 [ERROR]: uncaughtException: Cannot read properties of undefined (reading 'error')
TypeError: Cannot read properties of undefined (reading 'error')
    at D:\pratice\node-server\config\connectDatabase\connectDatabase.js:8:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 11:57:23 [ERROR]: uncaughtException: Cannot read properties of undefined (reading 'error')
TypeError: Cannot read properties of undefined (reading 'error')
    at exports.getMembersByProjectId (D:\pratice\node-server\controllers\membersController.js:139:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 11:58:20 [ERROR]: uncaughtException: Cannot read properties of undefined (reading 'error')
TypeError: Cannot read properties of undefined (reading 'error')
    at exports.loginUser (D:\pratice\node-server\controllers\authController.js:55:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 13:48:35 [ERROR]: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\pratice\node-server\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\pratice\node-server\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\pratice\node-server\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\pratice\node-server\index.js:53:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2025-01-17 13:49:13 [ERROR]: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\pratice\node-server\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\pratice\node-server\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\pratice\node-server\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\pratice\node-server\index.js:53:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2025-01-17 13:49:40 [ERROR]: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\pratice\node-server\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\pratice\node-server\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\pratice\node-server\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\pratice\node-server\index.js:53:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2025-01-17 13:49:59 [ERROR]: uncaughtException: Router.use() requires a middleware function but got a Object
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\pratice\node-server\node_modules\express\lib\router\index.js:469:13)
    at Function.<anonymous> (D:\pratice\node-server\node_modules\express\lib\application.js:227:21)
    at Array.forEach (<anonymous>)
    at Function.use (D:\pratice\node-server\node_modules\express\lib\application.js:224:7)
    at Object.<anonymous> (D:\pratice\node-server\index.js:53:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2025-01-17 13:50:22 [ERROR]: uncaughtException: Cannot find module '../config/logger'
Require stack:
- D:\pratice\node-server\controllers\notificationController.js
- D:\pratice\node-server\routes\notificationRoutes.js
- D:\pratice\node-server\routes\index.js
- D:\pratice\node-server\index.js
Error: Cannot find module '../config/logger'
Require stack:
- D:\pratice\node-server\controllers\notificationController.js
- D:\pratice\node-server\routes\notificationRoutes.js
- D:\pratice\node-server\routes\index.js
- D:\pratice\node-server\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\notificationController.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
2025-01-17 14:10:04 [ERROR]: uncaughtException: mongoose is not defined
ReferenceError: mongoose is not defined
    at Object.<anonymous> (D:\pratice\node-server\models\NotificationRecipientModel.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\controllers\notificationController.js:2:31)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2025-01-17 14:43:21 [ERROR]: uncaughtException: sendError is not defined
ReferenceError: sendError is not defined
    at exports.createNotification (D:\pratice\node-server\controllers\notificationController.js:26:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 14:44:11 [ERROR]: uncaughtException: sendError is not defined
ReferenceError: sendError is not defined
    at exports.createNotification (D:\pratice\node-server\controllers\notificationController.js:26:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 14:46:17 [ERROR]: uncaughtException: sendError is not defined
ReferenceError: sendError is not defined
    at exports.createNotification (D:\pratice\node-server\controllers\notificationController.js:26:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-17 14:55:22 [ERROR]: uncaughtException: sendError is not defined
ReferenceError: sendError is not defined
    at exports.getNotifications (D:\pratice\node-server\controllers\notificationController.js:38:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-21 23:13:34 [ERROR]: uncaughtException: Route.get() requires a callback function but got a [object Undefined]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as get] (D:\pratice\node-server\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\node-server\routes\taskRoutes.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\node-server\routes\index.js:10:20)
2025-02-05 23:06:46 [ERROR]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\index.js:69:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-02-05 23:07:35 [ERROR]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\index.js:69:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-02-09 13:37:39 [ERROR]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\index.js:69:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-02-09 13:38:51 [ERROR]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\index.js:69:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-02-09 13:45:51 [ERROR]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\index.js:69:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
2025-02-09 20:39:29 [ERROR]: uncaughtException: sendError is not defined
ReferenceError: sendError is not defined
    at exports.getNotificationByUserId (D:\pratice\Azi_Management_system_BE\controllers\notificationController.js:140:9)
    at Layer.handle [as handle_request] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\route.js:149:13)
    at D:\pratice\Azi_Management_system_BE\middlewares\authMiddleware.js:15:9
    at D:\pratice\Azi_Management_system_BE\node_modules\jsonwebtoken\verify.js:261:12
    at getSecret (D:\pratice\Azi_Management_system_BE\node_modules\jsonwebtoken\verify.js:97:14)
    at module.exports [as verify] (D:\pratice\Azi_Management_system_BE\node_modules\jsonwebtoken\verify.js:101:10)
    at authenticateToken (D:\pratice\Azi_Management_system_BE\middlewares\authMiddleware.js:10:9)
    at Layer.handle [as handle_request] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\route.js:149:13)
2025-02-09 21:47:37 [ERROR]: uncaughtException: Route.put() requires a callback function but got a [object Undefined]
Error: Route.put() requires a callback function but got a [object Undefined]
    at Route.<computed> [as put] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as put] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\routes\notificationRoutes.js:20:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\routes\index.js:12:28)
2025-02-09 21:50:24 [ERROR]: uncaughtException: Route.put() requires a callback function but got a [object Undefined]
Error: Route.put() requires a callback function but got a [object Undefined]
    at Route.<computed> [as put] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as put] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\routes\notificationRoutes.js:20:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\routes\index.js:12:28)
2025-02-09 21:55:16 [ERROR]: uncaughtException: Route.put() requires a callback function but got a [object Undefined]
Error: Route.put() requires a callback function but got a [object Undefined]
    at Route.<computed> [as put] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\route.js:216:15)
    at proto.<computed> [as put] (D:\pratice\Azi_Management_system_BE\node_modules\express\lib\router\index.js:521:19)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\routes\notificationRoutes.js:20:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\pratice\Azi_Management_system_BE\routes\index.js:12:28)
